// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordering.proto

package iroha.ordering.proto;

public final class Ordering {
  private Ordering() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ordering.proto\022\024iroha.ordering.proto\032\013" +
      "block.proto\032\016proposal.proto\032\033google/prot" +
      "obuf/empty.proto2[\n\031OrderingGateTranspor" +
      "tGrpc\022>\n\nonProposal\022\030.iroha.protocol.Pro" +
      "posal\032\026.google.protobuf.Empty2d\n\034Orderin" +
      "gServiceTransportGrpc\022D\n\ronTransaction\022\033" +
      ".iroha.protocol.Transaction\032\026.google.pro" +
      "tobuf.Emptyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          iroha.protocol.BlockOuterClass.getDescriptor(),
          iroha.protocol.ProposalOuterClass.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    iroha.protocol.BlockOuterClass.getDescriptor();
    iroha.protocol.ProposalOuterClass.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
